/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SecureIPFSMarketplace__factory } from "./SecureIPFSMarketplace__factory";
export { SecureIPFSReference__factory } from "./SecureIPFSReference__factory";
