/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SecureIPFSReference } from "./SecureIPFSReference";
export * as factories from "./factories";
export { SecureIPFSReference__factory } from "./factories/SecureIPFSReference__factory";
